name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in the format `v1.2.3`'
        required: true
        type: string
permissions:
  contents: write
  packages: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: 0.12
          cache-dependency-path: requirements.typ
      - name: Compile Typst files
        run: |
          typst compile --font-path=assets/fonts main.typ kval_darbs_kristians_cagulis_kc22015.pdf
          typst compile --font-path=assets/fonts documentary_page.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            kval_darbs_kristians_cagulis_kc22015.pdf
            documentary_page.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"
