name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in the format `v1.2.3`'
        required: true
        type: string
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install required fonts
        run: |
          sudo apt-get update
          # Install Times New Roman
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer

          mkdir -p ~/.local/share/fonts
          cp -r assets/fonts/* ~/.local/share/fonts/
          fc-cache -f -v
      - name: Compile main.typ
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            main.typ
            documentary_page.typ
      - name: Rename main.pdf
        run: mv main.pdf kval_darbs_kristians_cagulis_kc22015.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            *.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"
